
sudo: required

services:
  - docker

env:
  COMPOSE_VERSION: 1.7.1

before_install:
 - sudo apt-get update
 - sudo apt-get purge --yes docker-engine
 - sudo apt-get install --yes --force-yes docker-engine
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin

language: node_js

node_js:
  - "4"
  - "6"
  - "0.12"

script:
  - "sudo docker-compose up -d"
  - "./node_modules/.bin/vows --spec test/mongodb-driver-test.js"
  - "sudo docker-compose stop"
